create table if not exists rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  unit text,
  pic_name text,
  description text,
  status text not null default 'pending',
  checked_at timestamptz
);

create table if not exists assets (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  code text not null unique,
  name text not null,
  qty integer not null default 0,
  registered_qty integer not null default 0,
  condition text not null default 'Baik',
  created_at timestamptz not null default now()
);

create table if not exists inventory_checks (
  id bigint generated by default as identity primary key,
  teacher_name text not null,
  room_id bigint not null references rooms(id) on delete cascade,
  room_code text not null,
  room_name text not null,
  unit text,
  checked_at timestamptz not null default now()
);

-- Jalankan juga pada database yang tabelnya sudah dibuat sebelumnya.
alter table rooms add column if not exists unit text;
alter table rooms add column if not exists pic_name text;
alter table inventory_checks add column if not exists unit text;

create table if not exists inventory_check_items (
  id bigint generated by default as identity primary key,
  inventory_check_id bigint not null references inventory_checks(id) on delete cascade,
  asset_id bigint references assets(id) on delete set null,
  asset_code text not null,
  asset_name text not null,
  item_unit text not null default 'Unit',
  registered_qty integer not null default 0,
  actual_qty integer not null default 0,
  exists boolean not null default true,
  difference integer not null default 0,
  condition text not null default 'Baik',
  note text
);

alter table inventory_check_items add column if not exists item_unit text not null default 'Unit';

create index if not exists inventory_checks_room_checked_idx
  on inventory_checks (room_id, checked_at desc);

create index if not exists inventory_check_items_check_idx
  on inventory_check_items (inventory_check_id);
