create table if not exists rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  status text not null default 'pending',
  checked_at timestamptz
);

create table if not exists assets (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  code text not null unique,
  name text not null,
  qty integer not null default 0,
  registered_qty integer not null default 0,
  condition text not null default 'Baik',
  created_at timestamptz not null default now()
);

create table if not exists inventory_checks (
  id bigint generated by default as identity primary key,
  teacher_name text not null,
  room_id bigint not null references rooms(id) on delete cascade,
  room_code text not null,
  room_name text not null,
  checked_at timestamptz not null default now()
);

create table if not exists inventory_check_items (
  id bigint generated by default as identity primary key,
  inventory_check_id bigint not null references inventory_checks(id) on delete cascade,
  asset_id bigint references assets(id) on delete set null,
  asset_code text not null,
  asset_name text not null,
  registered_qty integer not null default 0,
  actual_qty integer not null default 0,
  exists boolean not null default true,
  difference integer not null default 0,
  condition text not null default 'Baik',
  note text
);

insert into rooms (code, name, description)
values
  ('R-001', 'Ruang Kelas 7A', 'Gedung A - Lantai 1'),
  ('R-002', 'Ruang Kelas 7B', 'Gedung A - Lantai 1')
on conflict (code) do nothing;

insert into assets (room_id, code, name, qty, registered_qty, condition)
select rooms.id, data.code, data.name, data.qty, data.qty, 'Baik'
from rooms
join (
  values
    ('R-001', 'AST-0001', 'Meja Guru', 1),
    ('R-001', 'AST-0002', 'Kursi Guru', 1),
    ('R-001', 'AST-0003', 'Meja Siswa', 18),
    ('R-002', 'AST-0010', 'Meja Guru', 1),
    ('R-002', 'AST-0011', 'Kursi Guru', 1)
) as data(room_code, code, name, qty)
  on rooms.code = data.room_code
on conflict (code) do nothing;
